M48
; DRILL file {KiCad (6.0.10)} date Fri Feb 17 09:19:31 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T09:19:31-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.0Y-2.7
X5.0Y-2.7
X5.2Y-2.8
X5.2Y-3.2
X5.2Y-3.2
X5.291Y-2.991
X5.3Y-3.2
X5.5Y-3.3
X5.5Y-3.3
X5.6Y-2.3
X5.7Y-3.5
X5.8Y-3.0
X5.8Y-3.0
X6.3Y-3.2
T2
X5.4Y-1.6
X5.6Y-1.6
T0
M30
